site:
  title: Dev Center Documentation
  start_page: ROOT:index.adoc
content:
  sources:
    - url: ../..
      branches: HEAD
      start_path: docs/modules
      worktrees: true
      edit_url: false
output:
  dir: ../build/site
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: []
asciidoc:
  attributes:
    experimental: ''
    page-pagination: ''

